=== panser/JavaBeginWebServices/10/10-JAXB/people.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="4"/>
						<xs:enumeration value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="people">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="David"/>
				<xs:enumeration value="Ivan"/>
				<xs:enumeration value="Katya"/>
				<xs:enumeration value="Michele"/>
				<xs:enumeration value="Nikolay"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== panser/JavaBeginWebServices/10/10-JAXB/people.xml
<?xml version="1.0" encoding="UTF-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Sergey/Documents/NetBeansProjects/JavaBeginWebServices/10/people.xsd">
	<person id="1">
		<name>Ivan</name>
	</person>
	<person id="2">
		<name>Nikolay</name>
	</person>
	<person id="3">
		<name>David</name>
	</person>
	<person id="4">
		<name>Michele</name>
	</person>
	<person id="5">
		<name>Katya</name>
	</person>
</people>
